import 'package:build/build.dart';
import 'package:dart_style/dart_style.dart';
import 'package:source_gen/source_gen.dart';
import 'package:analyzer/dart/element/element.dart';
import 'dart:core';

import 'src/anotations.dart';
import 'src/generators/space_generators.dart';

export 'src/anotations.dart';

Builder neatGenerator(BuilderOptions options) {
  final formater = DartFormatter();
  return PartBuilder(
    [NeatGenerator()],
    ".nt.dart",
    formatOutput: formater.format,
    header: """
// Generated by neat
//
// This file has been generated
// Do not modify by hand
""",
  );
}

// Runs for anything annotated as deprecated
class NeatGenerator extends GeneratorForAnnotation<NeatAnotation> {
  @override
  String generateForAnnotatedElement(
    Element element,
    ConstantReader anotation,
    __,
  ) {
    //TODO: parse config
    if (element is VariableElement) {
      return SpaceWidgetGenerator.tryGenerate(
        element,
        NeatAnotation(),
      );
    }
    throw ("@neat anotation should only be used on a plublic class");
  }
}
