import 'package:build/build.dart';
import 'package:dart_style/dart_style.dart';
import 'package:source_gen/source_gen.dart';
import 'dart:core';
import 'generators/space_widgets_generator.dart';

//TODO: padding extensions ?
//TODO: image widget/extensions ?

const String header = """
// Generated by neat
//
// This file has been generated
// Do not modify by hand
""";

const String import = """
import 'package:flutter/material.dart';
""";

Builder neatGenerator(BuilderOptions options) {
  final formater = DartFormatter();

  return PartBuilder(
    [
      SpaceWidgetsGenerator(),
    ],
    ".nt.dart",
    formatOutput: formater.format,
    header: header,
  );
}
